/*
 * Bedrock Views Module Configuration
 *
 * Copyright (c) 2012-2015 Digital Bazaar, Inc. All rights reserved.
 */
var config = require('bedrock').config;
var path = require('path');
require('bedrock-requirejs');

config.views = {};

// less config
config.views.less = {};
config.views.less.compile = {};
config.views.less.compile.options = {
  strictMath: true,
  sourceMap: false,
  outputSourceFiles: false
};
config.views.less.compile.order = ['bootstrap', 'font-awesome'];
config.views.less.compile.packages = {
  'font-awesome': {
    files: ['less/font-awesome.less']
  }
};
config.views.less.compile.files = [];
var componentsUrl = config.requirejs.bower.componentsUrl;
config.views.less.compile.vars = {
  '@fa-font-path': componentsUrl + '/font-awesome/fonts/',
  '@icon-font-path': componentsUrl + '/bootstrap/dist/fonts/'
};
config.views.less.compile.out = path.join(__dirname, '..', 'bedrock-views.css');

// css config
config.views.css = {};
config.views.css.optimize = {};
config.views.css.optimize.options = {};
config.views.css.optimize.out = path.join(
  __dirname, '..', 'bedrock-views.min.css');

// angular config
config.views.angular = {};
config.views.angular.optimize = {};
config.views.angular.optimize.templates = {};
// custom package configurations
config.views.angular.optimize.templates.packages = {};
// Example: (glob patterns are package-relative)
// config.views.optimize.angular.templates.packages.package_name = {
//   src: ['include/glob/**/*.html', '!exclude/glob/**.*.html']
// };
// package-relative default glob patterns, for any auto-detected packages these
// patterns will be appended to the package path to include or exclude
// templates; to exclude prepend '!' to the pattern
config.views.angular.optimize.templates.src = [
  '**/*.html',
  '!node_modules/**/*.html',
  '!bower_components/**/*.html'
];
// packages and files to specifically ignore when auto-detecting templates
// files must be full paths
config.views.angular.optimize.templates.ignore = {};
config.views.angular.optimize.templates.ignore.packages = ['forge'];
config.views.angular.optimize.templates.ignore.files = [];
// the angular module to add the templates to
config.views.angular.optimize.templates.module = 'bedrock.templates';
config.views.angular.optimize.templates.out = path.join(
  __dirname, '..', 'bedrock-angular-templates.js');
// htmlmin options
config.views.angular.optimize.templates.htmlmin = {
  collapseBooleanAttributes: false,
  collapseWhitespace: true,
  removeAttributeQuotes: false,
  removeComments: true,
  removeEmptyAttributes: false,
  removeEmptyElements: false,
  removeRedundantAttributes: false,
  removeScriptTypeAttributes: false,
  removeStyleLinkTypeAttributes: false,
  removeOptionalTags: false
};

// TODO: refactor some of these config settings into other modules

// branding config
config.brand = {};
config.brand.name = 'Bedrock';

// requirejs config
config.requirejs.config.deps.push('bedrock-angular');
config.requirejs.bower.ignore.push(
  'es5-shim',
//  'jquery.bedrock',
  'jquery-migrate',
  'bedrock-angular-identity');
// TODO: remove need for custom paths
config.requirejs.config.paths.forge = componentsUrl + '/forge/js';
config.requirejs.optimize.config.paths.forge =
  path.join(config.requirejs.bower.bowerrc.directory, 'forge', 'js');
// TODO: can these shims be autogenerated somehow?
config.requirejs.config.shim.jquery = {exports: 'jQuery'};
//config.requirejs.config.shim['jquery.bedrock'] = {deps: ['jquery']};
//config.requirejs.config.shim['jquery.migrate'] = {deps: ['jquery.bedrock']};
config.requirejs.config.shim.bootstrap = {deps: ['jquery', 'jquery-migrate']};
config.requirejs.config.shim.angular = {exports: 'angular', deps: ['jquery']};
config.requirejs.config.shim.bootstrap = {deps: ['jquery']};

config.views.vars = {};
config.views.cache = false;
config.views.paths = [
  path.join(__dirname, '..', 'views')
];

// authentication config
// see config.server.session for session config
// TODO: is this in the right config namespace?
config.views.authentication = {};
config.views.authentication.httpSignature = {};
config.views.authentication.httpSignature.enabled = true;

config.views.browserVersions = {
  IE: {major: 8, minor: 0},
  Firefox: {major: 3, minor: 6},
  Opera: {major: 10, minor: 6},
  Safari: {major: 4, minor: 0},
  Chrome: {major: 17, minor: 0}
};

config.views.vars = {
  productionMode: false,
  minify: false,
  baseUri: config.server.baseUri,
  serviceHost: config.server.host,
  serviceDomain: config.server.domain,
  supportDomain: config.server.domain,
  googleAnalytics: {
    enabled: false,
    account: ''
  },
  session: {
    loaded: false,
    auth: false
  },
  pageLayout: 'normal',
  debug: true,
  title: config.brand.name,
  siteTitle: config.brand.name,
  redirect: true,
  style: {
    brand: {
      alt: config.brand.name,
      src: componentsUrl + '/bedrock-angular/img/bedrock.png',
      height: '24',
      width: '182'
    }
  },
  // TODO: rename to something more along the lines of "shared" or "public"
  // client-side data
  clientData: {
    baseUri: config.server.baseUri,
    siteTitle: config.brand.name,
    productionMode: false,
    demoWarningUrl: 'https://bedrock.dev/wiki/Demo_Warning',
    // key generation config
    keygen: {
      bits: 2048
    },
    flags: {
      enableCreateIdentity: true
    },
    forms: {
      vocabs: []
    },
    angular: {
      templates: {
        overrides: {}
      }
    }
  },
  // contact and social media details
  // blog, email, facebook, github, googlePlus, irc, twitter, youtube
  //   *: {label: '...', url: '...'}
  //   email: {..., email: '...'}
  contact: {}
};

config.views.routes = [
  ['/', 'index.html'],
  '/about',
  '/legal',
  '/contact',
  ['/help', 'help/index.html']
];
