/*
 * Bedrock Views Module Configuration
 *
 * Copyright (c) 2012-2015 Digital Bazaar, Inc. All rights reserved.
 */
var config = require('bedrock').config;
var path = require('path');
require('bedrock-requirejs');

config.views = {};

// less variables
config.views.less = {};
config.views.less.compile = {};
config.views.less.compile.options = {
  strictMath: true,
  sourceMap: false,
  outputSourceFiles: false
};
config.views.less.compile.files = [];
config.views.less.compile.vars = {
  '@fa-font-path': '/bower-components/font-awesome/fonts/',
  '@icon-font-path': '/bower-components/bootstrap/dist/fonts/'
};
config.views.less.compile.output = 'bedrock-views.css';

// TODO: refactor some of these config settings into other modules

// branding config
config.brand = {};
config.brand.name = 'Bedrock';

// requirejs config
config.requirejs.config.deps.push('bedrock-angular');
config.requirejs.bower.ignore.push(
  'es5-shim',
//  'jquery.bedrock',
  'jquery-migrate',
  'bedrock-angular-identity');
// TODO: remove need for custom paths
config.requirejs.config.paths.forge = '/bower-components/forge/js';
// TODO: can these shims be autogenerated somehow?
config.requirejs.config.shim.jquery = {exports: 'jQuery'};
//config.requirejs.config.shim['jquery.bedrock'] = {deps: ['jquery']};
//config.requirejs.config.shim['jquery.migrate'] = {deps: ['jquery.bedrock']};
config.requirejs.config.shim.bootstrap = {deps: ['jquery', 'jquery-migrate']};
config.requirejs.config.shim.angular = {exports: 'angular', deps: ['jquery']};
config.requirejs.config.shim.bootstrap = {deps: ['jquery']};

// website config
config.website = {};

// views config
config.website.views = {};
config.website.views.vars = {};
config.website.views.cache = false;
config.website.views.paths = [
  path.join(__dirname, '..', 'views')
];

// authentication config
// see config.server.session for session config
config.website.authentication = {};
config.website.authentication.httpSignature = {};
config.website.authentication.httpSignature.enabled = true;

config.website.browserVersions = {
  IE: {major: 8, minor: 0},
  Firefox: {major: 3, minor: 6},
  Opera: {major: 10, minor: 6},
  Safari: {major: 4, minor: 0},
  Chrome: {major: 17, minor: 0}
};

config.website.views.vars = {
  productionMode: false,
  minify: false,
  baseUri: config.server.baseUri,
  serviceHost: config.server.host,
  serviceDomain: config.server.domain,
  supportDomain: config.server.domain,
  googleAnalytics: {
    enabled: false,
    account: ''
  },
  session: {
    loaded: false,
    auth: false
  },
  pageLayout: 'normal',
  debug: true,
  title: config.brand.name,
  siteTitle: config.brand.name,
  redirect: true,
  style: {
    brand: {
      alt: config.brand.name,
      src: '/bower-components/bedrock-angular/img/bedrock.png',
      height: '24',
      width: '182'
    }
  },
  // TODO: rename to something more along the lines of "shared" or "public"
  // client-side data
  clientData: {
    baseUri: config.server.baseUri,
    siteTitle: config.brand.name,
    productionMode: false,
    demoWarningUrl: 'https://bedrock.dev/wiki/Demo_Warning',
    // key generation config
    keygen: {
      bits: 2048
    },
    flags: {
      enableCreateIdentity: true
    },
    forms: {
      vocabs: []
    }
  },
  // contact and social media details
  // blog, email, facebook, github, googlePlus, irc, twitter, youtube
  //   *: {label: '...', url: '...'}
  //   email: {..., email: '...'}
  contact: {}
};

config.website.views.routes = [
  ['/', 'index.html'],
  '/about',
  '/legal',
  '/contact',
  ['/help', 'help/index.html']
];
