/*
 * Bedrock Views Module Configuration
 *
 * Copyright (c) 2012-2015 Digital Bazaar, Inc. All rights reserved.
 */
var config = require('bedrock').config;
var path = require('path');

// dependencies
require('bedrock-server');
require('bedrock-requirejs');

config.views = {};

// return 503 Service Unavailable response or page for all requests
config.views.serviceUnavailable = false;

// less config
config.views.less = {};
config.views.less.compile = {};
config.views.less.compile.options = {
  strictMath: true,
  sourceMap: false,
  outputSourceFiles: false
};
config.views.less.compile.order = ['bootstrap', 'font-awesome'];
config.views.less.compile.packages = {
  'font-awesome': {
    files: ['less/font-awesome.less']
  }
};
config.views.less.compile.files = [];
var componentsUrl = config.requirejs.bower.componentsUrl;
config.views.less.compile.vars = {
  '@fa-font-path': componentsUrl + '/font-awesome/fonts/',
  '@icon-font-path': componentsUrl + '/bootstrap/dist/fonts/'
};
config.views.less.compile.out = path.join(__dirname, '..', 'bedrock-views.css');

// css config
config.views.css = {};
config.views.css.optimize = {};
config.views.css.optimize.options = {};
config.views.css.optimize.out = path.join(
  __dirname, '..', 'bedrock-views.min.css');

// angular config
config.views.angular = {};
config.views.angular.optimize = {};
config.views.angular.optimize.templates = {};
// custom package configurations
config.views.angular.optimize.templates.packages = {};
// Example: (glob patterns are package-relative)
// config.views.optimize.angular.templates.packages.package_name = {
//   src: ['include/glob/**/*.html', '!exclude/glob/**.*.html']
// };
// package-relative default glob patterns, for any auto-detected packages these
// patterns will be appended to the package path to include or exclude
// templates; to exclude prepend '!' to the pattern
config.views.angular.optimize.templates.src = [
  '**/*.html',
  '!node_modules/**/*.html',
  '!bower_components/**/*.html'
];
// packages and files to specifically ignore when auto-detecting templates
// files must be full paths
config.views.angular.optimize.templates.ignore = {};
config.views.angular.optimize.templates.ignore.packages = ['forge'];
config.views.angular.optimize.templates.ignore.files = [];
// the angular module to add the templates to
config.views.angular.optimize.templates.module = 'bedrock.templates';
config.views.angular.optimize.templates.out = path.join(
  __dirname, '..', 'bedrock-angular-templates.js');
// htmlmin options
config.views.angular.optimize.templates.htmlmin = {
  collapseBooleanAttributes: false,
  collapseWhitespace: true,
  removeAttributeQuotes: false,
  removeComments: true,
  removeEmptyAttributes: false,
  removeEmptyElements: false,
  removeRedundantAttributes: false,
  removeScriptTypeAttributes: false,
  removeStyleLinkTypeAttributes: false,
  removeOptionalTags: false
};

// TODO: refactor some of these config settings into other modules

// branding config
config.views.brand = {};
config.views.brand.name = 'Bedrock';

// TODO: backwards compatibility, remove brand at top level of config
config.brand = config.views.brand;

// requirejs config
config.requirejs.config.deps.push('bedrock-angular');
config.requirejs.bower.ignore.push(
  'es5-shim',
  'bedrock-angular-identity');
// TODO: can these shims be autogenerated somehow?
config.requirejs.config.shim.jquery = {exports: 'jQuery'};
config.requirejs.config.shim.bootstrap = {deps: ['jquery']};
config.requirejs.config.shim.angular = {exports: 'angular', deps: ['jquery']};

config.views.cache = false;
config.views.paths = [
  path.join(__dirname, '..', 'views')
];

config.views.browserVersions = {
  IE: {major: 8, minor: 0},
  Firefox: {major: 3, minor: 6},
  Opera: {major: 10, minor: 6},
  Safari: {major: 4, minor: 0},
  Chrome: {major: 17, minor: 0}
};

config.views.vars = {
  angular: {
    templates: {
      // maps a template URL to a different template URL that overrides it
      // template URLs should be module-relative; do not include a base
      // path as these are auto-filled when scripts are unoptimized and
      // they are absent when they are optimized:
      // bedrock-angular/foo.html => my-module/replace-foo.html (good)
      // /bower-components/bedrock-angular/foo.html => ... (bad)
      overrides: {}
    }
  },
  baseUri: config.server.baseUri,
  // contact and social media details
  // blog, email, facebook, github, googlePlus, irc, twitter, youtube
  //   *: {label: '...', url: '...'}
  //   email: {..., email: '...'}
  contact: {},
  contextUrls: {},
  contextMap: {
    'https://w3id.org/security/v1':
      config.server.baseUri + '/contexts/security-v1.jsonld'
  },
  copyright: {
    show: true,
    agent: {
      id: 'http://digitalbazaar.com/contact#company',
      name: 'Digital Bazaar, Inc.',
      url: 'http://digitalbazaar.com/'
    },
    date: '2015'
  },
  footer: {
    show: true,
    docs: {
      show: true,
      link: '/docs',
      label: 'API'
    }
  },
  debug: true,
  demoWarningUrl: 'https://bedrock.dev/wiki/Demo_Warning',
  keygen: {
    // key generation config
    bits: 2048
  },
  flags: {
    enableCreateIdentity: true
  },
  forms: {
    vocabs: []
  },
  googleAnalytics: {
    enabled: false,
    account: ''
  },
  minify: false,
  pageLayout: 'normal',
  title: config.brand.name,
  siteTitle: config.brand.name,
  style: {
    brand: {
      alt: config.brand.name,
      src: componentsUrl + '/bedrock-angular/img/bedrock.png',
      height: '24',
      width: '182'
    }
  },
  supportDomain: config.server.domain,
  // private variables aren't sent to the client
  _private: {}
};

config.views.routes = [
  ['/', 'index.html'],
  '/about',
  '/legal',
  '/contact',
  ['/help', 'help/index.html']
];
